export const headers = [
    {
        "label": "Date",
        "name": "date",
        "type": "string"
    },
    {
        "label": "Supplier",
        "name": "supplier",
        "type": "string"
    },
    {
        "label": "Manufacturer",
        "name": "manufacturer",
        "type": "string"
    },
    {
        "label": "Model",
        "name": "model",
        "type": "string"
    },
    {
        "label": "Colour",
        "name": "colour",
        "type": "string"
    },
    {
        "label": "Battery",
        "name": "battery",
        "type": "string"
    },
    {
        "label": "Grade",
        "name": "grade",
        "type": "string"
    },
    {
        "label": "Notes",
        "name": "notes",
        "type": "string"
    },
    {
        "label": "Serial",
        "name": "imei   ",
        "type": "string"
    },
    {
        "label": "Cost",
        "name": "cost",
        "type": "number"
    },
    {
        "label": "Est. Sale",
        "name": "est_sale",
        "type": "number"
    },
    {
        "label": "Location",
        "name": "location",
        "type": "string"
    }
]

export const data = [
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Dell",
        "model": "Pavilion x360",
        "colour": "Titanium",
        "battery": "C",
        "grade": "A-",
        "notes": "Check screen",
        "serial": "3536827166",
        "cost": 123.86,
        "est_sale": 187,
        "location": "Bin #19 - (11 / 20)",
        "id": 1,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Samsung",
        "model": "Galaxy S21 FE 5G",
        "colour": "Titanium",
        "battery": "A",
        "grade": "B",
        "notes": "New",
        "serial": "F9FT837873",
        "cost": 58.97,
        "est_sale": 202,
        "location": "Bin #18 - (16 / 20)"
        ,
        "id": 2,
    },
    {
        "date": "2025-02-13",
        "supplier": "Quantum Lifecycle",
        "manufacturer": "Dell",
        "model": "iPad 5th Gen 32GB",
        "colour": "White",
        "battery": "B",
        "grade": "A",
        "notes": "Refurbished",
        "serial": "3523904960",
        "cost": 67.65,
        "est_sale": 217,
        "location": "Bin #15 - (4 / 20)",
        "id": 3,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Dell",
        "model": "Pavilion x360",
        "colour": "Titanium",
        "battery": "C",
        "grade": "A-",
        "notes": "Check screen",
        "serial": "3536827166",
        "cost": 123.86,
        "est_sale": 187,
        "location": "Bin #19 - (11 / 20)",
        "id": 4,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Samsung",
        "model": "Galaxy S21 FE 5G",
        "colour": "Titanium",
        "battery": "A",
        "grade": "B",
        "notes": "New",
        "serial": "F9FT837873",
        "cost": 58.97,
        "est_sale": 202,
        "location": "Bin #18 - (16 / 20)",
        "id": 5,
    },
    {
        "date": "2025-02-13",
        "supplier": "Quantum Lifecycle",
        "manufacturer": "Dell",
        "model": "iPad 5th Gen 32GB",
        "colour": "White",
        "battery": "B",
        "grade": "A",
        "notes": "Refurbished",
        "serial": "3523904960",
        "cost": 67.65,
        "est_sale": 217,
        "location": "Bin #15 - (4 / 20)",
        "id": 6,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Dell",
        "model": "Pavilion x360",
        "colour": "Titanium",
        "battery": "C",
        "grade": "A-",
        "notes": "Check screen",
        "serial": "3536827166",
        "cost": 123.86,
        "est_sale": 187,
        "location": "Bin #19 - (11 / 20)",
        "id": 7,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Samsung",
        "model": "Galaxy S21 FE 5G",
        "colour": "Titanium",
        "battery": "A",
        "grade": "B",
        "notes": "New",
        "serial": "F9FT837873",
        "cost": 58.97,
        "est_sale": 202,
        "location": "Bin #18 - (16 / 20)",
        "id": 8,
    },
    {
        "date": "2025-02-13",
        "supplier": "Quantum Lifecycle",
        "manufacturer": "Dell",
        "model": "iPad 5th Gen 32GB",
        "colour": "White",
        "battery": "B",
        "grade": "A",
        "notes": "Refurbished",
        "serial": "3523904960",
        "cost": 67.65,
        "est_sale": 217,
        "location": "Bin #15 - (4 / 20)",
        "id": 9,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Dell",
        "model": "Pavilion x360",
        "colour": "Titanium",
        "battery": "C",
        "grade": "A-",
        "notes": "Check screen",
        "serial": "3536827166",
        "cost": 123.86,
        "est_sale": 187,
        "location": "Bin #19 - (11 / 20)",
        "id": 10,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Samsung",
        "model": "Galaxy S21 FE 5G",
        "colour": "Titanium",
        "battery": "A",
        "grade": "B",
        "notes": "New",
        "serial": "F9FT837873",
        "cost": 58.97,
        "est_sale": 202,
        "location": "Bin #18 - (16 / 20)",
        "id": 11,
    },
    {
        "date": "2025-02-13",
        "supplier": "Quantum Lifecycle",
        "manufacturer": "Dell",
        "model": "iPad 5th Gen 32GB",
        "colour": "White",
        "battery": "B",
        "grade": "A",
        "notes": "Refurbished",
        "serial": "3523904960",
        "cost": 67.65,
        "est_sale": 217,
        "location": "Bin #15 - (4 / 20)",
        "id": 12,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Dell",
        "model": "Pavilion x360",
        "colour": "Titanium",
        "battery": "C",
        "grade": "A-",
        "notes": "Check screen",
        "serial": "3536827166",
        "cost": 123.86,
        "est_sale": 187,
        "location": "Bin #19 - (11 / 20)",
        "id": 13,
    },
    {
        "date": "2025-02-13",
        "supplier": "EcoTech",
        "manufacturer": "Samsung",
        "model": "Galaxy S21 FE 5G",
        "colour": "Titanium",
        "battery": "A",
        "grade": "B",
        "notes": "New",
        "serial": "F9FT837873",
        "cost": 58.97,
        "est_sale": 202,
        "location": "Bin #18 - (16 / 20)",
        "id": 14,
    },
    {
        "date": "2025-02-13",
        "supplier": "Quantum Lifecycle",
        "manufacturer": "Dell",
        "model": "iPad 5th Gen 32GB",
        "colour": "White",
        "battery": "B",
        "grade": "A",
        "notes": "Refurbished",
        "serial": "3523904960",
        "cost": 67.65,
        "est_sale": 217,
        "location": "Bin #15 - (4 / 20)",
        "id": 15,
    },
  
]